# Generated by Django 2.2.11 on 2020-03-13 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('is_team_member', models.BooleanField()),
                ('is_test_user', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user auth')),
            ],
        ),
    ]
